source "http://rubygems.org"

# Declare your gem's dependencies in mix-rails.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# jquery-rails is used by the dummy application
gem "jquery-rails"
gem 'colorbox-rails'

gem 'enumerize'

gem 'activevalidators'

gem "i18n_routing", "~> 0.6.2"

gem 'rails-i18n'

# TODO: Create two new to separate the mix-rails-core(class api) from the mix-rails-orm(database-access)
gem 'mongoid'
# mongoid should be loaded before cancan
gem "cancan"
gem 'mongoid_slug'
gem 'bson_ext'
gem 'mongo'
gem 'carrierwave-mongoid'
gem 'mini_magick'
gem 'haml_coffee_assets'

gem 'breadcrumbs'
gem 'simple-navigation'
gem 'simple-navigation-bootstrap'
gem 'datagrid'
gem 'will_paginate_mongoid'
gem 'coffee-script'
#gem 'sass-rails'

group :test do
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'mongoid-rspec'
end


group :development do
  
end

gem 'rspec-rails', :group => [:test, :development]

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'debugger'
