source "http://rubygems.org"

group :test, :development do
  gem "rspec-rails", "~> 2.0"
end


# Declare your gem's dependencies in admix.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec


# jquery-rails is used by the dummy application

gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'haml-rails'
gem 'coffee-script'
gem 'inherited_resources'
gem 'simple_form'
gem 'datagrid'
gem 'will_paginate_mongoid'

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'debugger'
